config:
  state:
    backend: local
    options:
      stateFile: devstream.state
tools:
  - name: repo-scaffolding
    instanceID: myapp1
    options:
      destinationRepo:
        org: [[env GITHUB_ORG]]
        name: [[env APP]]
        branch: main
        scmType: github
        token: [[env ORG_ADMIN_TOKEN]]
      sourceRepo:
        org: anees-mscs-org
        name: template-go-backend-db-aws
        scmType: github
      vars:
        ImageRepoUser: [[env DOCKERHUB_USER]]
        ImageRepo: [[env IMAGE_REPO]]
        Host: [[env HOST]]
        DbVersion: [[env DB_VERSION]]
        DbSize: [[env DB_SIZE]]
        GitHubOrg: [[env GITHUB_ORG]]
        GitHubUser: [[env GITHUB_USER]]
